### ISSUE TITLE
Cannot call method 'getUUID' of undefined

### ISSUE THREAD

**Issue by sharq1** [intercom/intercom-rails#153]
Some of our clients get following exception:
```
Uncaught TypeError: Cannot call method 'getUUID' of undefined
```
Because of that chat is not working.
Any ideas how to solve this?
At the moment I'm unable to get the stack trace, but it would be possible in a ~2 days time if necessary.

**Comment by RuairiK** [comment]
Hi (again),

I've done some digging and it seems likely that this is related to a known internal issue. I've spoken to the developers working on the issue who've told me a stack trace would be really helpful if you could provide one.  Also any other info you could provide, browser versions etc would be great.

When you say chat is broken, is it completely unusable? Most other reports of this error only mention the error being noticed, without a seriously detrimental effect on the messenger.

Thanks,
Ruairí.

**Comment by sharq1** [comment]
Here you go @RuairiK 

TypeError: Cannot call method 'getUUID' of undefined
    at i._connectionUuidForResponse (https://js.intercomcdn.com/intercom.bd89200b.js:14:25979)
    at i._onClose (https://js.intercomcdn.com/intercom.bd89200b.js:14:21606)
    at se (https://js.intercomcdn.com/intercom.bd89200b.js:15:24260)
    at ae (https://js.intercomcdn.com/intercom.bd89200b.js:15:23276)
    at le (https://js.intercomcdn.com/intercom.bd89200b.js:15:25004)
    at ce (https://js.intercomcdn.com/intercom.bd89200b.js:15:24532)
    at WebSocket.S.fe.onclose (https://js.intercomcdn.com/intercom.bd89200b.js:15:8581)
    at S (https://js.intercomcdn.com/intercom.bd89200b.js:15:9289)
    at b (https://js.intercomcdn.com/intercom.bd89200b.js:14:30565)
    at execute (https://js.intercomcdn.com/intercom.bd89200b.js:15:26890)

**Comment by sharq1** [comment]
The chat is completely unusable because of this.
I believe this happens only in Firefox, but I might be wrong.

**Comment by RuairiK** [comment]
Hi,

Thanks for the stack trace. I've passed it on to the team working on that issue.

The issue of chat not working in firefox sounds unrelated. It's more likely to be something to do with your integration. Could you email team@intercom.io so we can take a look?

**Comment by sharq1** [comment]
Thank you, I will.

I checked that again, and it indeed is unrelated, as the getUUID error goes off only on Android devices. Example:

```
Browser:  	Android Android Browser 4.2
User agent:	Mozilla/5.0 (Linux; U; Android 4.2.2; en-gb; GT-P5110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

**Comment by miriyas** [comment]
Uncaught TypeError: Cannot call method 'getUUID' of undefined

User-Agent: Mozilla/5.0 (Linux; U; Android 4.3; ko-kr; SHV-E210K Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 NAVER(inapp; search; 390; 6.4.5)

same errors

**Comment by hbj** [comment]
Same error (happens sometimes):

```
TypeError: Cannot call method 'getUUID' of undefined
  at i.<anonymous>(/intercom.32bdf3f5.js:15:26396)
  at i._createSubscription(/intercom.32bdf3f5.js:15:27927)
  at Object.n.subscribe(/intercom.32bdf3f5.js:17:2145)
  at execute(/intercom.32bdf3f5.js:17:1543)
  at b(/intercom.32bdf3f5.js:16:5249)
  at S(/intercom.32bdf3f5.js:16:15982)
  at WebSocket.S.fe.onclose(/intercom.32bdf3f5.js:16:15274)
  at ce(/intercom.32bdf3f5.js:16:31225)
  at le(/intercom.32bdf3f5.js:16:31697)
  at ae(/intercom.32bdf3f5.js:16:29969)
  at se(/intercom.32bdf3f5.js:16:30953)
  at i._onClose(/intercom.32bdf3f5.js:15:28309)
  at i._connectionUuidForResponse(/intercom.32bdf3f5.js:16:663)
```

User agent:

```
Mozilla/5.0 (Linux; U; Android 4.3; en-gb; SAMSUNG GT-I9300/I9300XXUGNB5 Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

**Comment by jarrodz** [comment]
I'm getting the same error:

```
TypeError: Cannot call method 'getUUID' of undefined
  at XMLHttpRequest.wrapped(/scripts/599d200d.vendor.js:51637:29)
  at i.<anonymous>(/intercom.21e03ea4.js:15:26335)
  at i._createSubscription(/intercom.21e03ea4.js:15:27866)
  at Object.n.subscribe(/intercom.21e03ea4.js:17:2112)
  at execute(/intercom.21e03ea4.js:17:1510)
  at b(/intercom.21e03ea4.js:16:5182)
  at S(/intercom.21e03ea4.js:16:15915)
  at WebSocket.S.fe.onclose(/intercom.21e03ea4.js:16:15207)
  at ce(/intercom.21e03ea4.js:16:31158)
  at le(/intercom.21e03ea4.js:16:31630)
  at ae(/intercom.21e03ea4.js:16:29902)
  at se(/intercom.21e03ea4.js:16:30886)
  at i._onClose(/intercom.21e03ea4.js:15:28248)
  at i._connectionUuidForResponse(/intercom.21e03ea4.js:16:596)
```
```
Mozilla/5.0 (Linux; U; Android 4.2.1; en-us; Micromax A116 Build/JOP40D) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 UCBrowser/9.8.0.435 U3/0.8.0 Mobile Safari/533.1
```

**Comment by GeyseR** [comment]
Same error on our installation:
```
TypeError: Cannot call method 'getUUID' of undefined
  at i.<anonymous>(/intercom.3a37c1b0.js:15:27577)
  at i._createSubscription(/intercom.3a37c1b0.js:15:29108)
  at Object.n.subscribe(/intercom.3a37c1b0.js:17:3356)
  at execute(/intercom.3a37c1b0.js:17:2754)
  at b(/intercom.3a37c1b0.js:16:6441)
  at S(/intercom.3a37c1b0.js:16:17174)
  at WebSocket.S.fe.onclose(/intercom.3a37c1b0.js:16:16466)
  at ce(/intercom.3a37c1b0.js:17:396)
  at le(/intercom.3a37c1b0.js:17:868)
  at ae(/intercom.3a37c1b0.js:16:31161)
  at se(/intercom.3a37c1b0.js:17:124)
  at i._onClose(/intercom.3a37c1b0.js:15:29490)
  at i._connectionUuidForResponse(/intercom.3a37c1b0.js:16:1855)
```
Happens in Android browser version 4.1-4.4,

**Comment by karensg** [comment]
+1

**Comment by benigeri** [comment]
:+1:

**Comment by cyrilchampier** [comment]
Retrieved from newrelic:
when these error occurs, the browser is always "Android Browser" (v 4.1 to 5.5)

**Comment by marcfalk** [comment]
+1 I've uploaded a screenshot from Sentry here: https://www.dropbox.com/s/bvyc80cfdefopay/1.png?dl=0

**Comment by asundlihardig** [comment]
I'm getting the same error.
Browser: 
`Android Android Browser 4.4`

User Error: 
`Mozilla/5.0 (Linux; U; Android 4.4.4; nb-no; GT-I9305 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

Stack Trace: 
`TypeError: Cannot call method 'getUUID' of undefined
    at i._subscriptionReconnect (https://js.intercomcdn.com/intercom.01dea911.js:15:22535)
    at i._reconnect (https://js.intercomcdn.com/intercom.01dea911.js:15:22437)
    at i._retry (https://js.intercomcdn.com/intercom.01dea911.js:15:22011)
    at i._onError (https://js.intercomcdn.com/intercom.01dea911.js:15:21185)
    at se (https://js.intercomcdn.com/intercom.01dea911.js:16:22418)
    at ae (https://js.intercomcdn.com/intercom.01dea911.js:16:22189)
    at le (https://js.intercomcdn.com/intercom.01dea911.js:16:23917)
    at N (https://js.intercomcdn.com/intercom.01dea911.js:16:9596)
    at M (https://js.intercomcdn.com/intercom.01dea911.js:16:10669)
    at WebSocket.S.fe.onclose (https://js.intercomcdn.com/intercom.01dea911.js:16:8055)`

**Comment by t7tong** [comment]
The internal issue has been fixed so I am closing this issue.

**Comment by tommoor** [comment]
We've just started seeing this in our logs as of yesterday, I can provide minimal stack traces if useful

**Comment by tommoor** [comment]
We've just started seeing this in our logs as of yesterday, a minimal stack trace:

```
TypeError: Cannot read property 'uuid' of null
  at e._connectionUuidForResponse(frame.60a9e0f0.js:24:9360)
  at e._onError(frame.60a9e0f0.js:24:5184)
  at se(frame.60a9e0f0.js:25:7155)
  at ae(frame.60a9e0f0.js:25:6926)
  at le(frame.60a9e0f0.js:25:8652)
  at A(frame.60a9e0f0.js:24:26349)
  at Y(frame.60a9e0f0.js:25:4740)
  at AtmosphereRequest.push(frame.60a9e0f0.js:25:10741)
  at e.publish(frame.60a9e0f0.js:24:1749)
  at ? (frame.60a9e0f0.js:23:30192)
  at e._publish(frame.60a9e0f0.js:23:30163)
  at e.sendEvent(frame.60a9e0f0.js:23:28317)
  at e._sendUserPresenceEvent(frame.60a9e0f0.js:23:30416)
  at e._userPresence(frame.60a9e0f0.js:23:30268)
  at e.setUserPresent(frame.60a9e0f0.js:23:29630)
  at ? (frame.60a9e0f0.js:17:10630)
  at ? (frame.60a9e0f0.js:17:1527)
  at ? (frame.60a9e0f0.js:17:9777)
  at ? (frame.60a9e0f0.js:29:7855)
  at onUserPresent(frame.60a9e0f0.js:5:14380)
  at HTMLDocument.l(frame.60a9e0f0.js:17:13384)
```

Perhaps this regressed? We started seeing it at this point in time:
![image](https://cloud.githubusercontent.com/assets/380914/22384667/30b8082c-e484-11e6-89d9-37e957070a14.png)

**Comment by StanBoyet** [comment]
It came back for us as well. Let me know if I can be of any help.
